import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const latin = Inter({ subsets: ['latin-ext'], weight: '400' })

export const metadata: Metadata = {
  title: 'Chimba tours',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={latin.className}>{children}</body>
    </html>
  )
}
